# Generated by Django 2.1.7 on 2023-08-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=128, null=True, unique=True)),
                ('email_verified', models.BooleanField()),
                ('mobilephone', models.CharField(max_length=32, null=True, unique=True)),
                ('mobilephone_verified', models.BooleanField()),
                ('active', models.BooleanField()),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=128, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('register_provider', models.CharField(blank=True, max_length=128, null=True)),
                ('photo', models.CharField(blank=True, max_length=4096, null=True)),
                ('deleted', models.BooleanField()),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('profession', models.CharField(max_length=256, null=True)),
                ('mobilephone_prefix', models.CharField(blank=True, max_length=128, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('must_update_password', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '"users"',
            },
        ),
    ]
